import React from "react";
import { ReceiptTable } from "@/components/dashboard/ReceiptTable";
import { ReceiptText, Link as LinkIcon } from "lucide-react";

export default function ReceiptsPage() {
  return (
    <div className="flex flex-col gap-6 h-full">
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-bold font-mono tracking-tight flex items-center gap-2">
          <ReceiptText className="w-6 h-6 text-primary" />
          ON-CHAIN_AUDIT
        </h1>
        <p className="text-sm font-mono text-muted-foreground">Immutable receipts of all trade executions and agent vetoes.</p>
      </div>

      <div className="bg-primary/5 border border-primary/20 rounded-lg p-4 flex items-start gap-4">
        <div className="bg-primary/20 p-2 rounded">
          <LinkIcon className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h3 className="font-mono font-bold text-sm text-foreground">Solana Txline Verification Active</h3>
          <p className="font-mono text-xs text-muted-foreground mt-1">
            Every action generated by the Orchestrator agent is hashed and committed to the Solana blockchain.
            This ensures mathematical proof of the decision timeline that cannot be altered retroactively.
          </p>
        </div>
      </div>

      <div className="flex-1 overflow-auto">
        <ReceiptTable />
      </div>
    </div>
  );
}
